spring.datasource.url = jdbc:mysql://localhost:3306/auth_app?useSSL=false&serverTimezone=UTC
spring.datasource.username = root
spring.datasource.password = 

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret = 5DbDftUc3FiMmRhuDkwldo7CUKlG1MOW4TtLHMXz4Vo=
jwt.expiration = 3600000

security.public-endpoint=/test/public,/api/usuario/registrar